### ISSUE TITLE
TypeError: unsupported format string passed to NoneType.__format__

### ISSUE THREAD

**Issue by EmilienM** [mandre/hubtty#18]
```
Traceback (most recent call last):
  File "/usr/local/bin/hubtty", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/hubtty/app.py", line 918, in main
    g.run()
  File "/usr/local/lib/python3.9/site-packages/hubtty/app.py", line 360, in run
    self.loop.run()
  File "/usr/lib64/python3.9/site-packages/urwid/main_loop.py", line 286, in run
    self._run()
  File "/usr/lib64/python3.9/site-packages/urwid/main_loop.py", line 384, in _run
    self.event_loop.run()
  File "/usr/lib64/python3.9/site-packages/urwid/main_loop.py", line 789, in run
    self._loop()
  File "/usr/lib64/python3.9/site-packages/urwid/main_loop.py", line 826, in _loop
    self._watch_files[fd]()
  File "/usr/lib64/python3.9/site-packages/urwid/raw_display.py", line 415, in <lambda>
    wrapper = lambda: self.parse_input(
  File "/usr/lib64/python3.9/site-packages/urwid/raw_display.py", line 514, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib64/python3.9/site-packages/urwid/main_loop.py", line 411, in _update
    self.process_input(keys)
  File "/usr/lib64/python3.9/site-packages/urwid/main_loop.py", line 512, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib64/python3.9/site-packages/urwid/container.py", line 1134, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/local/lib/python3.9/site-packages/hubtty/view/change_list.py", line 565, in keypress
    key = super(ChangeListView, self).keypress(size, key)
  File "/usr/lib64/python3.9/site-packages/urwid/container.py", line 1625, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/lib64/python3.9/site-packages/urwid/listbox.py", line 967, in keypress
    key = focus_widget.keypress((maxcol,),key)
  File "/usr/lib64/python3.9/site-packages/urwid/wimp.py", line 542, in keypress
    self._emit('click')
  File "/usr/lib64/python3.9/site-packages/urwid/widget.py", line 460, in _emit
    signals.emit_signal(self, name, self, *args)
  File "/usr/lib64/python3.9/site-packages/urwid/signals.py", line 264, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/usr/lib64/python3.9/site-packages/urwid/signals.py", line 294, in _call_callback
    return bool(callback(*args_to_pass))
  File "/usr/local/lib/python3.9/site-packages/hubtty/view/change_list.py", line 728, in onSelect
    view = view_change.ChangeView(self.app, change_key)
  File "/usr/local/lib/python3.9/site-packages/hubtty/view/change.py", line 565, in __init__
    self.refresh()
  File "/usr/local/lib/python3.9/site-packages/hubtty/view/change.py", line 758, in refresh
    self._updateTestResults(change, result_systems)
  File "/usr/local/lib/python3.9/site-packages/hubtty/view/change.py", line 780, in _updateTestResults
    line = [self._add_link(check.name, check.url), result]
  File "/usr/local/lib/python3.9/site-packages/hubtty/view/change.py", line 761, in _add_link
    link = mywid.Link('{:<42}'.format(name), 'link', 'focused-link')
TypeError: unsupported format string passed to NoneType.__format__
```

**Comment by EmilienM** [comment]
deleting the DB and restarting Hubtty from scratch with a new DB, no more issue.
